.TH "arguments" 3 "Sat Apr 3 2021" "Version v1.0" "OPaL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arguments
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBargs\fP [1]"
.br
.ti -1c
.RI "char * \fBlogfile\fP"
.br
.ti -1c
.RI "char * \fBdestfile\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 33 of file marc\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for OPaL from the source code\&.
