.TH "md__r_e_a_d_m_e" 3 "Sat Apr 3 2021" "Version v1.0" "OPaL" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- OPaL - OSU Programmin Language Compiler 
This is the repository for code by the team
.SH "Class: CS467-400 Spring 2021  Capstone Project"
.PP
.SH "Instructor:"
.PP
\fCBill Pfeil\fP
.SH "Team:"
.PP
.IP "\(bu" 2
\fCKedar Damle\fP 
.br

.IP "\(bu" 2
\fCJosh Mckerracher\fP 
.br

.IP "\(bu" 2
\fCSarah Leon\fP 
.br

.PP
.SS "Project tracking:"
\fCKanban board\fP
.SS "Coding style:"
.IP "\(bu" 2
\fCFormatting\fP
.IP "\(bu" 2
\fCDoxygen\fP
.PP
.SS "Installation:"
Untar the latest release of the compiler to a destination directory\&.
.SS "Usage:"
.IP "1." 4
Export LD_LIBRARY_PATH to include the build directory 
.br
 \fCexport LD_LIBRARY_PATH=build\fP 
.br

.IP "2." 4
Run binary with argument \fC--help\fP to display help and usage instructions 
.PP

